language: go

go:
  - tip

install:
  - go get github.com/justmao945/mallory/cmd/mallory

# TODO: add test mallory
script:

notifications:
  email:
    recipients:
      - justmao945@gmail.com
    on_success: change
    on_failure: always
